const STATIC_SVG_FILENAMES = [
  'alarm-clock-regular.svg',
  'arrow-rotate-right-solid.svg',
  'arrows-rotate-solid.svg',
  'arrows-to-circle-solid.svg',
  'bag-shopping-solid.svg',
  'book-solid.svg',
  'calendar-regular.svg',
  'candy-cane-solid.svg',
  'champagne-glasses-solid.svg',
  'chess-solid.svg',
  'compass-regular.svg',
  'crown-solid-full.svg',
  'diamond-solid.svg',
  'dragon-solid.svg',
  'expand-solid.svg',
  'ferry-solid.svg',
  'fort-awesome-brands-solid-full.svg',
  'ghost-solid-full.svg',
  'heart-solid.svg',
  'left-long-solid.svg',
  'maximize-solid.svg',
  'minimize-solid.svg',
  'moon-regular.svg',
  'music-solid.svg',
  'right-long-solid.svg',
  'suitcase-solid.svg',
  'temperature-arrow-down-solid.svg',
  'temperature-arrow-up-solid.svg',
  'torii-gate-solid.svg',
  'triangle-exclamation-solid.svg',
  'xmark-solid.svg',
  '伯伦斯法环_hat-wizard-solid-full.svg',
  '兽族联盟_paw-solid-full.svg',
  '奥古斯提姆帝国_landmark-flag-solid-full.svg',
  '瓦伦蒂亚_dungeon-solid-full.svg',
  '索伦蒂斯王国_chess-queen-regular-full.svg',
  '精灵文明_leaf-solid-full.svg',
  '诺斯加德联盟_snowflake-solid-full.svg',
  '萨赫拉联邦_sun-solid-full.svg',
  '翼民圣都_feather-solid-full.svg',
] as const;

export const ALL_SVG_FILENAMES = [...STATIC_SVG_FILENAMES].sort((left, right) =>
  left.localeCompare(right, 'zh-Hans-CN'),
);
