import { getActiveCalendarProfile } from '../profile';

export function buildCalendarVariableListEntryContent(): string {
  return [
    '---',
    '现有月历事件',
    '',
    '<calendar_variables_display>',
    '<%_ { _%>',
    '<%_',
    "  const rootPath = 'stat_data.事件.月历';",
    '  const calendar = getvar(rootPath, { defaults: { 临时: {}, 重复: {} } });',
    '',
    '  // 仅隐藏玩家手动标记为私有的事件；缺省或脏值按默认公开处理，避免旧变量被误过滤。',
    "  const isVisibleToLLM = function (event) { return String(_.get(event, '可见性', '')).trim() !== '仅玩家'; };",
    '  const normalizeDisplayImportance = function (value) {',
    "    const text = String(value || '').trim();",
    "    if (['重要且紧急', '重要不紧急', '不重要但紧急', '不重要不紧急'].includes(text)) return text;",
    "    if (text === '重要') return '重要且紧急';",
    "    if (text === '纪念') return '重要不紧急';",
    "    if (text === '普通') return '不重要不紧急';",
    "    return '';",
    '  };',
    '  const normalizeRepeatRuleClass = function (value) {',
    "    const text = String(value || '').trim();",
    "    return ['每天', '每周', '每月', '每年'].includes(text) ? text : '';",
    '  };',
    "  const removeEmptyValues = function (output) { return _.pickBy(_.mapValues(output, function (value) { return typeof value === 'string' ? value.trim() : value; }), function (value) { return value !== undefined && value !== null && value !== '' && !(_.isArray(value) && value.length === 0); }); };",
    '  const cleanEvent = function (event, bucketType) {',
    "    const keys = bucketType === '重复'",
    "      ? ['标题', '内容', '时间', '结束时间', '重要度', '标签']",
    "      : ['标题', '内容', '时间', '结束时间', '重要度', '标签'];",
    '    const output = _.pick(event, keys);',
    '    const normalizedImportance = normalizeDisplayImportance(output.重要度);',
    '    if (normalizedImportance) {',
    '      output.重要度 = normalizedImportance;',
    '    } else {',
    '      delete output.重要度;',
    '    }',
    "    if (bucketType === '重复') {",
    "      output.重复规则分类 = normalizeRepeatRuleClass(_.get(event, '重复规则分类', _.get(event, '重复规则', '')));",
    '    }',
    '    return removeEmptyValues(output);',
    '  };',
    '  const normalizeBucket = function (bucket, bucketType) {',
    '    return _.chain(_.isObject(bucket) ? bucket : {})',
    '      .pickBy(isVisibleToLLM)',
    '      .mapValues(function (event) { return cleanEvent(event, bucketType); })',
    '      .pickBy(function (event) { return !_.isEmpty(event); })',
    '      .value();',
    '  };',
    '',
    '  const displayOutput = {',
    '    事件: {',
    '      月历: {',
    "        临时: normalizeBucket(_.get(calendar, '临时'), '临时'),",
    "        重复: normalizeBucket(_.get(calendar, '重复'), '重复'),",
    '      },',
    '    },',
    '  };',
    '  print(YAML.stringify(displayOutput, { blockQuote: \'literal\' }));',
    '_%>',
    '<%_ } _%>',
    '</calendar_variables_display>',
  ].join('\n');
}

export function buildCalendarUpdateRulesEntryContent(): string {
  const profile = getActiveCalendarProfile();
  const timeExamples = profile.worldbook.updateRuleTimeExamples.map(example => `\`${example}\``).join('、');
  const tempPath = profile.paths.tempEvents.replace(/^stat_data\./, '');
  const repeatPath = profile.paths.repeatEvents.replace(/^stat_data\./, '');
  return [
    '---',
    '月历变量更新规则:',
    '  重要度:',
    '    重要且紧急: 会明显影响当前主线、任务成败、角色安全，且时间接近或正在发生',
    '    重要不紧急: 对主线、长期关系、关键承诺或大型计划重要，但不是马上要处理',
    '    不重要但紧急: 时间接近，需要提醒或处理，但后果较轻',
    '    不重要不紧急: 普通日程、背景安排、轻量纪念或低影响事件',
    '',
    `  ${tempPath} / ${repeatPath}:`,
    '    check:',
    '      - 月历只记录具有明确时间锚点的事项；标签用于表达月历显示分类，可由{{user}}按需要自定义；标签不是任务类型，也不能替代任务列表的状态、进展、目标、奖励',
    "      - <%- (function () { const systemCore = String(getvar('系统核心', { defaults: '' }) || '').trim(); const systemCoreName = String(getvar('系统核心名', { defaults: '' }) || '').trim(); const hasSystemCore = Boolean(systemCore) && systemCore !== 'null核心'; const hasSystemCoreName = Boolean(systemCoreName) && systemCoreName.toLowerCase() !== 'null'; if (hasSystemCore && hasSystemCoreName) { return '当出现适合记录进月历的新事项时，应先由' + systemCoreName + '简短询问{{user}}是否需要记录；未经{{user}}明确同意，不得自动新增、修改或删除月历事件；若刚询问但{{user}}尚未回应，本轮不得更新月历'; } return '只有{{user}}明确要求记录、明确同意记录、明确要求修改或明确要求删除时，才可新增、修改或删除月历事件'; }()) %>",
    '      - 新增事件前必须先检查现有事件是否已经记录同一事项；临时事件以`标题+时间+结束时间`查重，重复事件以`标题+重复规则分类+时间+结束时间`查重',
    '      - 若已存在同一事项，必须沿用原ID更新，不得新增重复事件',
    '      - 新事件需生成唯一ID（必须匹配正则 `/^[a-zA-Z0-9_]+$/`）；ID应稳定、可复用，避免仅因标题措辞变化而改用新ID',
    '      - 标题、内容、时间必须互相一致；事件需保持原子化，不要将多个无关安排塞进同一个事件',
    `      - ${buildCalendarTagRuleText()}`,
    '      - 时间与结束时间不得写自由句子或相对时间，例如“明天”“三天后”“月底”“课程结束后”',
    '      - 结束时间可留空；如填写，必须与时间使用同类格式',
    '      - 重要度必须按上方“重要度”定义选择；不确定时优先使用“不重要不紧急”',
    '      - 若同一事项同时也是任务，只在月历中记录时间提醒、约定或截止，不记录任务奖励、结算状态、执行步骤或详细进展',
    '      - 不得因为任务列表中存在“主线/支线/限时”等任务而自动新增月历事件；只有任务出现明确日期、时间、周期或截止日，且{{user}}要求或确认记录时才写入月历',
    '',
    `  ${tempPath}:`,
    '    type: |-',
    '      {',
    '        [ID: string]: {',
    '          标题: string;',
    '          内容: string; // 客观视角，详细描述、备忘信息',
    '          时间: string; // 一次性时间：完整世界时间、完整世界日期、或月日锚点',
    '          结束时间: optional[string];',
    "          重要度: optional['重要且紧急' | '重要不紧急' | '不重要但紧急' | '不重要不紧急'];",
    '          标签: optional[string[]];',
    '        }',
    '      }',
    '    check:',
    `      - 只存一次性或临时事件；如果事件会规律重复，必须写入 \`${repeatPath}\``,
    `      - 时间只能使用：${timeExamples}`,
    '      - 若事件时间、标题或内容被{{user}}确认改期/改名/修正，优先更新原ID，不得删除后重建',
    '      - 若事件已发生、取消或不再具有提醒价值，应移除该事件',
    '      - 不得把只有任务目标但没有明确时间锚点的事项写入临时事件',
    '',
    `  ${repeatPath}:`,
    '    重复规则分类:',
    '      每天: 时间写 `每天`，结束时间留空',
    '      每周: 时间写 `每周一` 或 `每周一、三`，结束时间留空',
    '      每月: 时间写 `每月10日`，结束时间留空或写 `每月17日`',
    '      每年: 时间写 `每年1月10日`，结束时间留空或写 `每年1月17日`',
    '    type: |-',
    '      {',
    '        [ID: string]: {',
    '          标题: string;',
    '          内容: string;',
    "          重复规则分类: '每天' | '每周' | '每月' | '每年';",
    '          时间: string;',
    '          结束时间: optional[string];',
    "          重要度: optional['重要且紧急' | '重要不紧急' | '不重要但紧急' | '不重要不紧急'];",
    '          标签: optional[string[]];',
    '        }',
    '      }',
    '    check:',
    `      - 只存规律重复事件；一次性事件必须写入 \`${tempPath}\``,
    '      - 时间与结束时间必须严格按 `重复规则分类` 填写',
    '      - 重复事件严禁使用包含具体年份的完整世界时间，例如“复兴纪元488年-6月5日”',
    '      - 不得把一次性任务截止日、单次约定或一次性旅行计划写成重复事件',
    `      - 若重复安排被{{user}}取消、停止或改为一次性安排，应移除重复事件或迁移为 \`${tempPath}\``,
  ].join('\n');
}

function buildCalendarTagRuleText(): string {
  const profile = getActiveCalendarProfile();
  return `标签优先复用已有标签；只有现有标签无法表达时才新增短标签。当前可用标签：<%- (function () { var calendar = getvar('${profile.paths.eventRoot}', { defaults: { 临时: {}, 重复: {} } }); var baseTags = ['主线', '支线', '课程', '约会', '节庆', '旅行', '比赛', '限时', '纪念']; var mirroredTags = getvar('calendar_float_store.runtime.known_tags', { defaults: [] }); var collectBucketTags = function (bucket) { return _.flatMap(_.values(_.isObject(bucket) ? bucket : {}), function (event) { return _.isArray(_.get(event, '标签')) ? _.get(event, '标签') : []; }); }; var tags = _.uniq([].concat(baseTags, _.isArray(mirroredTags) ? mirroredTags : [], collectBucketTags(_.get(calendar, '临时')), collectBucketTags(_.get(calendar, '重复'))).map(function (tag) { return String(tag || '').trim(); }).filter(Boolean)).sort(function (left, right) { return left.localeCompare(right, 'zh-CN'); }); return tags.length ? tags.join('、') : '暂无'; }()) %>`;
}
