export function buildCalendarVariableListEntryContent(): string {
  return [
    '---',
    '现有日历事件',
    '',
    '<calendar_variables_display>',
    '<%_',
    '(function () {',
    "  var rootPath = 'stat_data.事件.日历';",
    "  var calendar = getvar(rootPath, { defaults: { 临时: {}, 重复: {} } });",
    '',
    '  // 仅隐藏玩家手动标记为私有的事件；缺省或脏值按默认公开处理，避免旧变量被误过滤。',
    "  var isVisibleToLLM = function (event) { return String(_.get(event, '可见性', '')).trim() !== '仅玩家'; };",
    "  var normalizeDisplayImportance = function (value) {",
    "    var text = String(value || '').trim();",
    "    if (['重要且紧急', '重要不紧急', '不重要但紧急', '不重要不紧急'].includes(text)) return text;",
    "    if (text === '重要') return '重要且紧急';",
    "    if (text === '纪念') return '重要不紧急';",
    "    if (text === '普通') return '不重要不紧急';",
    "    return '';",
    '  };',
    "  var normalizeRepeatRuleClass = function (value) {",
    "    var text = String(value || '').trim();",
    "    return ['每天', '每周', '每月', '每年', '仅工作日'].includes(text) ? text : '';",
    '  };',
    "  var removeEmptyValues = function (output) { return _.pickBy(_.mapValues(output, function (value) { return typeof value === 'string' ? value.trim() : value; }), function (value) { return value !== undefined && value !== null && value !== '' && !(_.isArray(value) && value.length === 0); }); };",
    '  var cleanEvent = function (event, bucketType) {',
    "    var keys = bucketType === '重复'",
    "      ? ['标题', '内容', '时间', '结束时间', '重要度', '标签']",
    "      : ['标题', '内容', '时间', '结束时间', '重要度', '标签'];",
    '    var output = _.pick(event, keys);',
    "    var normalizedImportance = normalizeDisplayImportance(output.重要度);",
    '    if (normalizedImportance) {',
    '      output.重要度 = normalizedImportance;',
    '    } else {',
    '      delete output.重要度;',
    '    }',
    "    if (bucketType === '重复') {",
    "      output.重复规则分类 = normalizeRepeatRuleClass(_.get(event, '重复规则分类', _.get(event, '重复规则', '')));",
    '    }',
    '    return removeEmptyValues(output);',
    '  };',
    '  var normalizeBucket = function (bucket, bucketType) {',
    '    return _.chain(_.isObject(bucket) ? bucket : {})',
    '      .pickBy(isVisibleToLLM)',
    '      .mapValues(function (event) { return cleanEvent(event, bucketType); })',
    '      .pickBy(function (event) { return !_.isEmpty(event); })',
    '      .value();',
    '  };',
    '',
    '  var displayOutput = {',
    '    事件: {',
    '      日历: {',
    "        临时: normalizeBucket(_.get(calendar, '临时'), '临时'),",
    "        重复: normalizeBucket(_.get(calendar, '重复'), '重复'),",
    '      },',
    '    },',
    '  };',
    '  print(YAML.stringify(displayOutput, { blockQuote: \'literal\' }));',
    '}());',
    '_%>',
    '</calendar_variables_display>',
  ].join('\n');
}

export function buildCalendarUpdateRulesEntryContent(): string {
  return [
    '---',
    'calendar_variables_update_rules:',
    '    事件.日历.临时:',
    '        type: |-',
    '        {',
    '            [ID: string]: // 必须匹配regex: `/^[a-zA-Z0-9_]+$/`',
    '            {',
    '                标题: string;',
    '                内容: string; // 客观视角，详细描述、备忘信息',
    '                时间: string; // 只写一次性时间：完整世界时间（参照`世界-时间`）或月日锚点（如1月1日）',
    '                结束时间: optional[string]; // 可留空；跨日事件填同类格式，禁止写相对时间',
    "                重要度: optional['重要且紧急' | '重要不紧急' | '不重要但紧急' | '不重要不紧急'];",
    '                标签: optional[string[]];',
    '            }',
    '        }',
    '        check:',
    '        - 仅存一次性/临时事件；不得写“重复规则”字段，也不得把事件放入“重复”桶',
    '        - 时间只能使用预设模板：`复兴纪元488年-6月5日-星期三-09:00`、`复兴纪元488年-6月5日-星期三`、`6月5日`',
    '        - 结束时间只能使用同类模板，例如开始为完整世界时间则结束也用完整世界时间；开始为月日则结束也用月日',
    '        - 禁止自由句子和相对时间，例如“明天”“三天后”“每个月”“考试结束后”',
    '        - **ID 唯一性**：新事件需生成唯一 ID；更新现有事件必须沿用原 ID',
    '        - 如果事件会规律重复，必须改写到 `事件.日历.重复`，不要在临时事件里描述重复规律',
    ...buildCalendarTagRuleLines(),
    '        - 不要写“可见性”或“完成后”；这些是隐藏规则，缺省由玩家 UI 或脚本处理',
    '        - 不要写“类型”；事件分类交给“标签”表达，脚本会保留旧类型字段但不要求 LLM 维护',
    '        - 如果未指定“重要度 / 标签”，脚本会回落到默认值',
    '        - 需要保持适当原子化',
    '',
    '    事件.日历.重复:',
    '        type: |-',
    '        {',
    '            [ID: string]: // 必须匹配regex: `/^[a-zA-Z0-9_]+$/`',
    '            {',
    '                标题: string;',
    '                内容: string; // 客观视角，详细描述、备忘信息；若31日需跳过短月，在这里说明',
    "                重复规则分类: string; // only choose from '每天' | '每周' | '每月' | '每年' | '仅工作日'",
    '                时间: string; // 必须与“重复规则分类”严格匹配，只能使用下方预设模板',
    '                结束时间: optional[string]; // 只用于区间终点；必须与时间字段同类，不能写相对时间',
    "                重要度: optional['重要且紧急' | '重要不紧急' | '不重要但紧急' | '不重要不紧急'];",
    '                标签: optional[string[]];',
    '            }',
    '        }',
    '        check:',
    '        - 仅存规律重复事件；不得写 `重复规则` 或 `重复规则分类: 无`；一次性事件必须写入 `事件.日历.临时`',
    '        - 重复规则分类为“每天”时：`时间: 每天`，结束时间留空',
    '        - 重复规则分类为“仅工作日”时：`时间: 每个工作日`，结束时间留空',
    '        - 重复规则分类为“每周”时：`时间: 每周一` 或 `时间: 每周一、三、五`；不要写完整世界时间',
    '        - 重复规则分类为“每月”时：`时间: 每月10日`；月内区间用 `结束时间: 每月17日`',
    '        - 重复规则分类为“每年”时：`时间: 每年1月10日`；年度区间用 `结束时间: 每年1月17日`',
    '        - 标题、内容、时间必须互相一致，不要标题写每月、重复规则分类却写每周',
    '        - 禁止自由句子、完整世界时间和相对时间，例如“月底”“每隔几天”“复兴纪元488年-6月5日”“课程结束后”',
    '        - 每月31日遇到没有31日的月份会按当月最后一天处理；如果需要严格跳过短月，需在内容里说明',
    '        - 不要使用“仅节假日”，脚本目前没有可靠的通用节假日表',
    ...buildCalendarTagRuleLines(),
    '        - 不要写“可见性”或“完成后”；这些是隐藏规则，缺省由玩家 UI 或脚本处理',
    '        - 不要写“类型”；事件分类交给“标签”表达，脚本会保留旧类型字段但不要求 LLM 维护',
    '        - 如果未指定“重要度 / 标签”，脚本会回落到默认值',
    '        - 需要保持适当原子化',
  ].join('\n');
}

function buildCalendarTagRuleLines(): string[] {
  return [
    "        - 当前可用标签：<%- (function () { var calendar = getvar('stat_data.事件.日历', { defaults: { 临时: {}, 重复: {} } }); var baseTags = ['主线', '支线', '课程', '约会', '节庆', '旅行', '比赛', '限时', '纪念']; var mirroredTags = getvar('calendar_float_store.runtime.known_tags', { defaults: [] }); var collectBucketTags = function (bucket) { return _.flatMap(_.values(_.isObject(bucket) ? bucket : {}), function (event) { return _.isArray(_.get(event, '标签')) ? _.get(event, '标签') : []; }); }; var tags = _.uniq([].concat(baseTags, _.isArray(mirroredTags) ? mirroredTags : [], collectBucketTags(_.get(calendar, '临时')), collectBucketTags(_.get(calendar, '重复'))).map(function (tag) { return String(tag || '').trim(); }).filter(Boolean)).sort(function (left, right) { return left.localeCompare(right, 'zh-CN'); }); return tags.length ? tags.join('、') : '暂无'; }()) %>；优先复用已有标签，只有现有标签无法表达事件主题、用途或管理规则时才新增短标签；新增标签写入“标签”数组，脚本会在后续界面候选与管理流程中收录",
  ];
}
